services:
  redis:
    container_name: "vagasprajr-redis"
    image: redis:alpine
    env_file:
      - .env    
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    # Specify the redis.conf file to use and add a password.
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    ports:
      - "6380:6379"